@startuml [AS-IS] C4
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person_Ext(customer, "Customer", "Buys tickets and enters the park")
Person(employee, "Employee", "Manages ticket sales and validation")
System(ticketCounter, "Ticket Counter", "Handles manual ticket sales")
System(cashRegister, "Cash Register", "Logs ticket details manually")

Rel(customer, ticketCounter, "Requests and buys tickets")
Rel(ticketCounter, employee, "Confirms ticket availability")
Rel(employee, ticketCounter, "Provides ticket")
Rel(employee,cashRegister, "Records ticket\nsales")
Rel(customer, ticketCounter, "Receives paper\nticket")
Rel(cashRegister, employee, "Provides receipt\nfor sale")
@enduml