@startuml TicketCheckingProcess AS-IS

' As-Is Ticket Checking Process
  
|#eeaaaa|Customer|
 start
  :Customer approaches entry gate;
  :Customer waits in line;
|#9999cc|Employee|
  :Employee asks for ticket;
|Customer|
  :Customer hands over ticket;
|Employee|
  :Employee manually checks ticket;
  :Employee confirms ticket validity;
  if(Are there any ticket types\nthat require checking\nthe client documents?) then (Yes)
  :Check all of the needed documents;
  else (No)
  endif
|Employee|
  :Employee stamps or marks ticket;
  :Employee allows customer to proceed;
|Customer|
  :Customer enters the park;
  stop


@enduml
